### ISSUE TITLE
TypeError: this.abi.reduce is not a function

### ISSUE THREAD

**Issue by mandarvaze** [miguelmota/ethereum-input-data-decoder#14]
I'm getting the above error when I do in a javascript jupyter notebook: 
```
const result = decoder.decodeData('0x........');
/path/to/myproject/node_modules/ethereum-input-data-decoder/dist/index.js:89
      var result = this.abi.reduce(function (acc, obj) {
                            ^

TypeError: this.abi.reduce is not a function
    at InputDataDecoder.decodeData (/path/to/myproject/node_modules/ethereum-input-data-decoder/dist/index.js:89:29)
    at evalmachine.<anonymous>:1:24
    at Script.runInThisContext (vm.js:91:20)
    at Object.runInThisContext (vm.js:298:38)
    at run ([eval]:1002:15)
    at onRunRequest ([eval]:829:18)
    at onMessage ([eval]:789:13)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:807:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
I'm using version **0.0.12** of ethereum-input-data-decoder

Could this be because I'm using latest `solc` ?
One of the attributes of the `decoder` is listed as follows : 

```
compiler: 
      { name: 'solc',
        version: '0.4.24+commit.e67f0147.Emscripten.clang' }
```

I'll try to see if I have ABI generated using older version of `solc`

**Comment by mandarvaze** [comment]
Never mind. I figured out the problem.

I was passing the JSON file created by the build process. This JSON contains a lot more than `abi` (Most likely that is why the problem)
