### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by DavBE** [miguelmota/ethereum-input-data-decoder#44]
Hi,

I am getting the following error when running from command line : 

```C:\Users\User>ethereum-input-data-decoder --help
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\User\AppData\Roaming\npm\node_modules\ethereum-input-data-decoder\node_modules\meow\index.js
require() of ES modules is not supported.
require() of C:\Users\User\AppData\Roaming\npm\node_modules\ethereum-input-data-decoder\node_modules\meow\index.js from C:\Users\User\AppData\Roaming\npm\node_modules\ethereum-input-data-decoder\cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\User\AppData\Roaming\npm\node_modules\ethereum-input-data-decoder\node_modules\meow\package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\ethereum-input-data-decoder\cli.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

Am i missing something ?

Regards,

David

**Comment by miguelmota** [comment]
Should work again on the latest version
